### PR TITLE
Configure authentication for acls instead of tpg1

### PR DESCRIPTION
**Pull request by SlothOfAnarchy**

### CODE REVIEW

**Comment by SlothOfAnarchy** [comment]
bump. @Mr-Pi @dasJ @Scriptkiddi

**Comment by dasJ** [comment]
Again: Python is out of my area of knowledge. Ping @Mr-Pi @Scriptkiddi

**Comment by SlothOfAnarchy** [comment]
please review @Scriptkiddi @Mr-Pi

**Review by dasJ — APPROVED** [review]
I guess

**Pull request merged**
